name: Run Python Tests
on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          node-version: '16.x'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./python

      - name: Test with pytest
        run: pytest -vv
        working-directory: ./python
